
const REACHDEM_DATABASE_ID = process.env.NEXT_PUBLIC_APPWRITE_REACHDEM_DATABASE_ID as string;
const CAMPAIGNS_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_CAMPAIGN_STATS_COLLECTION_ID as string;



export {REACHDEM_DATABASE_ID, CAMPAIGNS_COLLECTION_ID}