// Constantes partagées pour les segments
export const MAILING_DATABASE_ID = process.env.NEXT_PUBLIC_APPWRITE_MAILING_DATABASE_ID as string
export const SEGMENTS_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_MAILING_SEGMENTS_COLLECTION_ID as string
export const CONTACT_SEGMENTS_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_MAILING_SEGMENT_CONTACTS_COLLECTION_ID as string
export const CONTACTS_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_MAILING_CONTACTS_COLLECTION_ID as string
